#!/usr/bin/env bash

# fail if any commands fails
set -x

# Execute checks:

readonly root_directory=`../../`

cd "${root_directory}"

find Sources -type f -name '*.swift' -exec md5 {} ';' | md5 > .pre_format_hash

swift test

swift run swiftformat .

swift run swiftlint autocorrect

find Sources -type f -name '*.swift' -exec md5 {} ';' | md5 > .post_format_hash

diff .pre_format_hash .post_format_hash > /dev/null || { echo \"File formatting modified\" ; rm .pre_format_hash ; rm .post_format_hash ; exit "${LINENO}"; }

rm .pre_format_hash ; rm .post_format_hash
