name: Test
on: push
jobs:
  build:
    name: Test
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.app/Contents/Developer
        run: swift test
